import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "@/components/ui/NavBar";
import SideBar from "@/components/ui/SideBar";
import Conten from "@/components/layout/Conten";
import Footer from "@/components/layout/Footer";
import SessionAuthProvider from "@/context/SessionAuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <NavBar />
      <SideBar />
      <Conten>{children}</Conten>
      <Footer />
    </>
  );
}
