import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import Screen from "@/components/layout/Screen";
import NavBar from "@/components/ui/NavBar";
import { SocketProvider } from "@/context/SocketContext";
import Content from "@/components/layout/Content";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <SocketProvider>
      <html lang="en">
        <body className={inter.className}>
          <Screen>
            <Content>
              <NavBar />
              {children}
            </Content>
          </Screen>
        </body>
      </html>
    </SocketProvider>
  );
}
